// =============================================================================
// MICRO-GENESIS TCG MARKET INTELLIGENCE - NEO4J SCHEMA
// =============================================================================
// A knowledge graph schema for autonomous TCG market research and price prediction.
// Supports the closed-loop discovery cycle: Hypothesis -> Data Collection -> Validation
// =============================================================================

// -----------------------------------------------------------------------------
// CONSTRAINTS & INDEXES
// -----------------------------------------------------------------------------

// Unique constraints for core entities
CREATE CONSTRAINT hypothesis_id IF NOT EXISTS FOR (h:Hypothesis) REQUIRE h.id IS UNIQUE;
CREATE CONSTRAINT task_id IF NOT EXISTS FOR (t:DataCollectionTask) REQUIRE t.id IS UNIQUE;
CREATE CONSTRAINT card_id IF NOT EXISTS FOR (c:Card) REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT set_id IF NOT EXISTS FOR (s:Set) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT price_id IF NOT EXISTS FOR (p:Price) REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT tournament_id IF NOT EXISTS FOR (t:Tournament) REQUIRE t.id IS UNIQUE;
CREATE CONSTRAINT deck_id IF NOT EXISTS FOR (d:Deck) REQUIRE d.id IS UNIQUE;
CREATE CONSTRAINT source_id IF NOT EXISTS FOR (s:DataSource) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT event_id IF NOT EXISTS FOR (e:MarketEvent) REQUIRE e.id IS UNIQUE;
CREATE CONSTRAINT insight_id IF NOT EXISTS FOR (i:Insight) REQUIRE i.id IS UNIQUE;
CREATE CONSTRAINT cycle_id IF NOT EXISTS FOR (c:DiscoveryCycle) REQUIRE c.id IS UNIQUE;

// Indexes for common queries
CREATE INDEX hypothesis_status IF NOT EXISTS FOR (h:Hypothesis) ON (h.status);
CREATE INDEX hypothesis_confidence IF NOT EXISTS FOR (h:Hypothesis) ON (h.confidence);
CREATE INDEX task_status IF NOT EXISTS FOR (t:DataCollectionTask) ON (t.status);
CREATE INDEX task_priority IF NOT EXISTS FOR (t:DataCollectionTask) ON (t.priority);
CREATE INDEX card_name IF NOT EXISTS FOR (c:Card) ON (c.name);
CREATE INDEX card_game IF NOT EXISTS FOR (c:Card) ON (c.game);
CREATE INDEX card_rarity IF NOT EXISTS FOR (c:Card) ON (c.rarity);
CREATE INDEX price_timestamp IF NOT EXISTS FOR (p:Price) ON (p.timestamp);
CREATE INDEX tournament_date IF NOT EXISTS FOR (t:Tournament) ON (t.date);
CREATE INDEX event_date IF NOT EXISTS FOR (e:MarketEvent) ON (e.date);
CREATE INDEX insight_timestamp IF NOT EXISTS FOR (i:Insight) ON (i.timestamp);

// Full-text search indexes
CREATE FULLTEXT INDEX hypothesis_text IF NOT EXISTS FOR (h:Hypothesis) ON EACH [h.text, h.reasoning];
CREATE FULLTEXT INDEX card_search IF NOT EXISTS FOR (c:Card) ON EACH [c.name, c.set_name, c.description];
CREATE FULLTEXT INDEX event_search IF NOT EXISTS FOR (e:MarketEvent) ON EACH [e.title, e.description];

// -----------------------------------------------------------------------------
// NODE LABELS & PROPERTIES
// -----------------------------------------------------------------------------

// Hypothesis Node - Generated by Claude 4.5 Opus
// Properties:
//   id: String (UUID)
//   text: String (The hypothesis statement)
//   reasoning: String (Claude's reasoning for this hypothesis)
//   confidence: Float (0.0 - 1.0)
//   status: String (Pending, InProgress, Validated, Rejected, Inconclusive)
//   category: String (Price, Tournament, Social, Grading, Release, Seasonal, etc.)
//   timeframe: String (Short-term, Medium-term, Long-term)
//   created_at: DateTime
//   updated_at: DateTime
//   validated_at: DateTime (null until validated)
//   validation_result: String (null until validated)
//   validation_confidence: Float (null until validated)

// DataCollectionTask Node - Tasks for Fara-7B agents
// Properties:
//   id: String (UUID)
//   type: String (PriceScrape, TournamentScrape, SocialScrape, NewsScrape, etc.)
//   target_url: String (URL to scrape)
//   target_data: String (Description of data to collect)
//   status: String (Pending, InProgress, Completed, Failed, Cancelled)
//   priority: Integer (1-10, higher = more urgent)
//   retries: Integer (Number of retry attempts)
//   max_retries: Integer (Maximum retry attempts)
//   created_at: DateTime
//   started_at: DateTime
//   completed_at: DateTime
//   error_message: String (null unless failed)
//   result_summary: String (Summary of collected data)

// Card Node - TCG Card data
// Properties:
//   id: String (Unique card ID, e.g., "pokemon-base-set-4-charizard")
//   name: String
//   game: String (Pokemon, MTG, YuGiOh, Lorcana, etc.)
//   set_name: String
//   set_code: String
//   card_number: String
//   rarity: String (Common, Uncommon, Rare, Ultra Rare, Secret Rare, etc.)
//   description: String
//   types: List<String> (Fire, Water, etc. for Pokemon)
//   attributes: Map (Game-specific attributes)
//   release_date: Date
//   is_graded_relevant: Boolean (True if commonly graded)
//   image_url: String

// Set Node - TCG Set data
// Properties:
//   id: String (Unique set ID)
//   name: String
//   code: String
//   game: String
//   release_date: Date
//   total_cards: Integer
//   description: String

// Price Node - Price point data
// Properties:
//   id: String (UUID)
//   price_usd: Float
//   price_eur: Float
//   condition: String (Near Mint, Lightly Played, etc.)
//   grading_company: String (PSA, BGS, CGC, etc. or null for raw)
//   grade: String (10, 9.5, 9, etc. or null for raw)
//   source: String (eBay, TCGPlayer, Cardmarket, etc.)
//   listing_type: String (BuyItNow, Auction, MarketPrice)
//   timestamp: DateTime
//   is_sale: Boolean (True if sold, False if listing)

// Tournament Node - Tournament event data
// Properties:
//   id: String (UUID)
//   name: String
//   game: String
//   format: String (Standard, Expanded, etc.)
//   date: Date
//   location: String
//   attendance: Integer
//   tier: String (Regional, National, World Championship, etc.)

// Deck Node - Tournament deck data
// Properties:
//   id: String (UUID)
//   name: String
//   archetype: String
//   player_name: String
//   placement: Integer
//   format: String

// DataSource Node - Source of collected data
// Properties:
//   id: String
//   name: String (eBay, TCGPlayer, Reddit, Twitter, etc.)
//   type: String (Marketplace, SocialMedia, News, Tournament)
//   base_url: String
//   reliability_score: Float (0.0 - 1.0)
//   last_scraped: DateTime
//   scrape_frequency: String (Hourly, Daily, Weekly)

// MarketEvent Node - Events that may affect prices
// Properties:
//   id: String (UUID)
//   title: String
//   description: String
//   type: String (SetRelease, BanList, Tournament, GameAnnouncement, Reprint, etc.)
//   date: Date
//   impact_assessment: String
//   expected_impact: Float (-1.0 to 1.0, negative = price decrease)

// Insight Node - AI-generated insights from data
// Properties:
//   id: String (UUID)
//   text: String
//   type: String (Trend, Anomaly, Correlation, Prediction)
//   confidence: Float (0.0 - 1.0)
//   timestamp: DateTime
//   source_model: String (Claude, Fara, etc.)

// DiscoveryCycle Node - Tracks discovery cycle execution
// Properties:
//   id: String (UUID)
//   cycle_number: Integer
//   status: String (Running, Completed, Failed)
//   started_at: DateTime
//   completed_at: DateTime
//   hypotheses_generated: Integer
//   tasks_created: Integer
//   tasks_completed: Integer
//   insights_generated: Integer
//   context: String (Initial context for the cycle)

// -----------------------------------------------------------------------------
// RELATIONSHIP TYPES
// -----------------------------------------------------------------------------

// Hypothesis relationships
// (h:Hypothesis)-[:GENERATED_IN]->(c:DiscoveryCycle)
// (h:Hypothesis)-[:ABOUT]->(c:Card)
// (h:Hypothesis)-[:ABOUT]->(s:Set)
// (h:Hypothesis)-[:ABOUT]->(t:Tournament)
// (h:Hypothesis)-[:ABOUT]->(e:MarketEvent)
// (h:Hypothesis)-[:REQUIRES_DATA]->(t:DataCollectionTask)
// (h:Hypothesis)-[:VALIDATED_BY]->(i:Insight)
// (h:Hypothesis)-[:DERIVED_FROM]->(h2:Hypothesis) - New hypothesis from old
// (h:Hypothesis)-[:CONTRADICTS]->(h2:Hypothesis)
// (h:Hypothesis)-[:SUPPORTS]->(h2:Hypothesis)

// DataCollectionTask relationships
// (t:DataCollectionTask)-[:TARGETS]->(s:DataSource)
// (t:DataCollectionTask)-[:COLLECTS_DATA_FOR]->(c:Card)
// (t:DataCollectionTask)-[:COLLECTS_DATA_FOR]->(t:Tournament)
// (t:DataCollectionTask)-[:PRODUCED]->(p:Price)
// (t:DataCollectionTask)-[:PRODUCED]->(i:Insight)
// (t:DataCollectionTask)-[:CREATED_IN]->(c:DiscoveryCycle)

// Card relationships
// (c:Card)-[:BELONGS_TO]->(s:Set)
// (c:Card)-[:EVOLVES_FROM]->(c2:Card) - Pokemon evolution chain
// (c:Card)-[:RELATED_TO]->(c2:Card) - Related cards (same character, etc.)
// (c:Card)-[:HAS_PRICE]->(p:Price)
// (c:Card)-[:PLAYED_IN]->(d:Deck)
// (c:Card)-[:AFFECTED_BY]->(e:MarketEvent)

// Set relationships
// (s:Set)-[:PRECEDED_BY]->(s2:Set)
// (s:Set)-[:FOLLOWED_BY]->(s2:Set)
// (s:Set)-[:RELEASED_IN]->(e:MarketEvent)

// Price relationships
// (p:Price)-[:FOR_CARD]->(c:Card)
// (p:Price)-[:FROM_SOURCE]->(s:DataSource)
// (p:Price)-[:RECORDED_AFTER]->(e:MarketEvent)

// Tournament relationships
// (t:Tournament)-[:FEATURED]->(d:Deck)
// (t:Tournament)-[:WON_BY]->(d:Deck)
// (t:Tournament)-[:AFFECTED_PRICE]->(c:Card)

// Deck relationships
// (d:Deck)-[:PLACED_IN]->(t:Tournament)
// (d:Deck)-[:CONTAINS]->(c:Card)

// MarketEvent relationships
// (e:MarketEvent)-[:IMPACTS]->(c:Card)
// (e:MarketEvent)-[:IMPACTS]->(s:Set)
// (e:MarketEvent)-[:TRIGGERS]->(h:Hypothesis)

// Insight relationships
// (i:Insight)-[:ABOUT]->(c:Card)
// (i:Insight)-[:ABOUT]->(s:Set)
// (i:Insight)-[:ABOUT]->(e:MarketEvent)
// (i:Insight)-[:GENERATED_IN]->(c:DiscoveryCycle)
// (i:Insight)-[:DERIVED_FROM]->(p:Price)
// (i:Insight)-[:VALIDATES]->(h:Hypothesis)
// (i:Insight)-[:INVALIDATES]->(h:Hypothesis)

// DiscoveryCycle relationships
// (c:DiscoveryCycle)-[:PREVIOUS]->(c2:DiscoveryCycle)
// (c:DiscoveryCycle)-[:NEXT]->(c2:DiscoveryCycle)

// -----------------------------------------------------------------------------
// SAMPLE SEED DATA
// -----------------------------------------------------------------------------

// Create a sample discovery cycle
MERGE (cycle:DiscoveryCycle {
    id: 'cycle-seed-001',
    cycle_number: 0,
    status: 'Completed',
    started_at: datetime(),
    completed_at: datetime(),
    hypotheses_generated: 0,
    tasks_created: 0,
    tasks_completed: 0,
    insights_generated: 0,
    context: 'System initialization'
});

// Create sample data sources
MERGE (ebay:DataSource {
    id: 'source-ebay',
    name: 'eBay',
    type: 'Marketplace',
    base_url: 'https://www.ebay.com',
    reliability_score: 0.85,
    scrape_frequency: 'Hourly'
});

MERGE (tcgplayer:DataSource {
    id: 'source-tcgplayer',
    name: 'TCGPlayer',
    type: 'Marketplace',
    base_url: 'https://www.tcgplayer.com',
    reliability_score: 0.95,
    scrape_frequency: 'Hourly'
});

MERGE (cardmarket:DataSource {
    id: 'source-cardmarket',
    name: 'Cardmarket',
    type: 'Marketplace',
    base_url: 'https://www.cardmarket.com',
    reliability_score: 0.90,
    scrape_frequency: 'Daily'
});

MERGE (reddit:DataSource {
    id: 'source-reddit',
    name: 'Reddit',
    type: 'SocialMedia',
    base_url: 'https://www.reddit.com',
    reliability_score: 0.60,
    scrape_frequency: 'Daily'
});

MERGE (twitter:DataSource {
    id: 'source-twitter',
    name: 'Twitter/X',
    type: 'SocialMedia',
    base_url: 'https://twitter.com',
    reliability_score: 0.55,
    scrape_frequency: 'Daily'
});

MERGE (limitless:DataSource {
    id: 'source-limitless',
    name: 'Limitless TCG',
    type: 'Tournament',
    base_url: 'https://limitlesstcg.com',
    reliability_score: 0.98,
    scrape_frequency: 'Daily'
});

// Create sample card (Charizard Base Set)
MERGE (charizard:Card {
    id: 'pokemon-base-set-4-charizard',
    name: 'Charizard',
    game: 'Pokemon',
    set_name: 'Base Set',
    set_code: 'BS',
    card_number: '4/102',
    rarity: 'Holo Rare',
    description: 'The iconic Charizard from the original Base Set',
    types: ['Fire', 'Flying'],
    release_date: date('1999-01-09'),
    is_graded_relevant: true
});

// Create sample set
MERGE (baseset:Set {
    id: 'pokemon-base-set',
    name: 'Base Set',
    code: 'BS',
    game: 'Pokemon',
    release_date: date('1999-01-09'),
    total_cards: 102,
    description: 'The original Pokemon Trading Card Game set'
});

// Create relationship
MATCH (c:Card {id: 'pokemon-base-set-4-charizard'})
MATCH (s:Set {id: 'pokemon-base-set'})
MERGE (c)-[:BELONGS_TO]->(s);

// -----------------------------------------------------------------------------
// UTILITY QUERIES
// -----------------------------------------------------------------------------

// Query to get pending hypotheses
// MATCH (h:Hypothesis {status: 'Pending'})
// RETURN h.id, h.text, h.confidence
// ORDER BY h.confidence DESC;

// Query to get pending data collection tasks
// MATCH (t:DataCollectionTask {status: 'Pending'})
// RETURN t.id, t.type, t.target_url, t.priority
// ORDER BY t.priority DESC;

// Query to get price history for a card
// MATCH (c:Card {id: 'pokemon-base-set-4-charizard'})-[:HAS_PRICE]->(p:Price)
// RETURN p.timestamp, p.price_usd, p.condition, p.grade, p.source
// ORDER BY p.timestamp DESC;

// Query to get hypothesis validation rate
// MATCH (h:Hypothesis)
// WITH h.status as status, count(*) as count
// RETURN status, count, toFloat(count) / sum(count) as percentage;

// Query to get top cards by price activity
// MATCH (c:Card)-[:HAS_PRICE]->(p:Price)
// WHERE p.timestamp > datetime() - duration('P7D')
// WITH c, count(p) as price_points, avg(p.price_usd) as avg_price
// RETURN c.name, c.game, price_points, avg_price
// ORDER BY price_points DESC
// LIMIT 20;
