/**
 * Insight Engine Schema - AI-Powered Market Intelligence
 *
 * Supports the Q1 2026 "Pro Subscription with predictive analytics" goal.
 * Provides persistence layer for:
 * - Perplexity-style AI-generated market reports with citations
 * - Sentiment tracking (Fear & Greed index)
 *
 * Note: Market Movers are handled by ./marketMovers.ts
 *
 * Reference: Apex Intelligence Center PRD - "AI-Powered Insights" feature
 */

import {
  pgTable,
  pgEnum,
  uuid,
  text,
  integer,
  timestamp,
  jsonb,
  index,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import type { InferSelectModel, InferInsertModel } from 'drizzle-orm';

// =============================================================================
// ENUMS
// =============================================================================

/**
 * Report types determine the depth, prompt strategy, and display format
 * - daily_snapshot: Brief morning market overview (free tier preview)
 * - weekly_deep_dive: Comprehensive analysis with predictions (Pro tier)
 * - flash_alert: Breaking news / sudden market movement (Pro tier)
 */
export const reportTypeEnum = pgEnum('report_type', [
  'daily_snapshot',
  'weekly_deep_dive',
  'flash_alert',
]);

/**
 * Sentiment label for human-readable display
 * Maps to score ranges: Extreme Fear (0-20), Fear (21-40), Neutral (41-60),
 * Greed (61-80), Extreme Greed (81-100)
 */
export const sentimentLabelEnum = pgEnum('sentiment_label', [
  'extreme_fear',
  'fear',
  'neutral',
  'greed',
  'extreme_greed',
]);

/**
 * Supported TCG games for market analysis
 */
export const tcgGameEnum = pgEnum('tcg_game', [
  'pokemon',
  'mtg',
  'lorcana',
  'yugioh',
  'one_piece',
  'flesh_and_blood',
]);

// =============================================================================
// MARKET REPORTS (The "Perplexity-Style" Content)
// =============================================================================

/**
 * Citation structure for Perplexity-style footnotes
 */
export interface MarketReportCitation {
  id: string; // Unique citation ID (e.g., "cite-1")
  source: string; // Source name (e.g., "TCGPlayer", "Reddit r/pkmntcg")
  url?: string; // Optional URL to source
  quote?: string; // Relevant quote from source
  relevance: number; // 0-1 score of how relevant this citation is
  accessedAt: string; // ISO timestamp when source was accessed
}

/**
 * AI metadata for tracking model performance and costs
 */
export interface MarketReportAIMetadata {
  modelId: string; // e.g., "gpt-4o", "claude-3-5-sonnet"
  promptVersion: string; // Version of the prompt template used
  tokensInput: number;
  tokensOutput: number;
  totalTokens: number;
  latencyMs: number; // Time to generate in milliseconds
  temperature: number; // Model temperature used
  ragSourceCount: number; // Number of RAG sources retrieved
}

/**
 * Market Reports table
 *
 * Stores AI-generated analysis to be served instantly to Pro users.
 * Caches expensive LLM computations to avoid per-request generation costs.
 *
 * Query patterns:
 * - Latest reports by game and type (Dashboard)
 * - Published reports feed (Blog/Content page)
 * - Historical reports for trend analysis
 */
export const marketReports = pgTable(
  'market_reports',
  {
    id: uuid('id').defaultRandom().primaryKey(),

    // Core content
    title: text('title').notNull(),
    slug: text('slug').notNull().unique(), // URL-safe identifier for the report

    // Report classification
    reportType: reportTypeEnum('report_type').notNull(),
    game: tcgGameEnum('game').notNull().default('pokemon'),

    // Rich content (Markdown) generated by the LLM
    content: text('content').notNull(),

    // Executive summary for preview cards (max 280 chars)
    summary: text('summary'),

    // Structured citations for the "Perplexity style" UI
    // Enables interactive footnotes in the frontend
    citations: jsonb('citations').$type<MarketReportCitation[]>().default([]),

    // Key takeaways (bullet points for quick scanning)
    keyTakeaways: jsonb('key_takeaways').$type<string[]>().default([]),

    // Featured cards mentioned in the report (for quick-links)
    featuredCardIds: jsonb('featured_card_ids').$type<string[]>().default([]),

    // AI metadata for debugging/refining prompts and cost tracking
    aiMetadata: jsonb('ai_metadata').$type<MarketReportAIMetadata>(),

    // SEO and engagement
    viewCount: integer('view_count').default(0).notNull(),
    shareCount: integer('share_count').default(0).notNull(),

    // Visibility control
    isPublished: text('is_published', { enum: ['draft', 'published', 'archived'] })
      .default('draft')
      .notNull(),

    // Lifecycle timestamps
    publishedAt: timestamp('published_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),

    // TTL for cache invalidation (when should this report be regenerated?)
    expiresAt: timestamp('expires_at', { withTimezone: true }),
  },
  (table) => ({
    // Fast lookup for dashboard: "Get latest Pokemon daily snapshot"
    gameTypeIdx: index('idx_market_reports_game_type').on(table.game, table.reportType),

    // Feed queries: "Get all published reports, newest first"
    publishedIdx: index('idx_market_reports_published').on(
      table.isPublished,
      table.publishedAt,
    ),

    // Slug lookup for direct URL access
    slugIdx: index('idx_market_reports_slug').on(table.slug),

    // Cache invalidation: "Find expired reports needing refresh"
    expiresIdx: index('idx_market_reports_expires').on(table.expiresAt),

    // Content discovery by type
    typeIdx: index('idx_market_reports_type').on(table.reportType),
  }),
);

// =============================================================================
// SENTIMENT TRACKER (Fear & Greed Index)
// =============================================================================

/**
 * Contributing factors that influence the sentiment score
 */
export interface SentimentFactor {
  name: string; // e.g., "Price Volatility", "Social Hype", "Sales Volume"
  weight: number; // How much this factor contributes (0-1)
  value: number; // The factor's current value (0-100)
  trend: 'rising' | 'falling' | 'stable';
  description?: string; // Human-readable explanation
}

/**
 * Sentiment Snapshots table
 *
 * Tracks the "Fear & Greed" index of the market over time.
 * Enables historical trend analysis and market timing insights.
 *
 * Score interpretation:
 * - 0-20: Extreme Fear (buying opportunity?)
 * - 21-40: Fear
 * - 41-60: Neutral
 * - 61-80: Greed
 * - 81-100: Extreme Greed (bubble territory?)
 */
export const sentimentSnapshots = pgTable(
  'sentiment_snapshots',
  {
    id: uuid('id').defaultRandom().primaryKey(),

    // Which market this sentiment applies to
    game: tcgGameEnum('game').notNull().default('pokemon'),

    // The headline number: 0-100 score
    score: integer('score').notNull(),

    // Human-readable label derived from score
    label: sentimentLabelEnum('label').notNull(),

    // Directional change from previous snapshot
    previousScore: integer('previous_score'),
    scoreChange: integer('score_change'), // Can be negative

    // Contributing factors with weighted breakdown
    // Enables "Why is the market fearful?" explanations
    factors: jsonb('factors').$type<SentimentFactor[]>().default([]),

    // Optional AI-generated narrative explaining the sentiment
    narrative: text('narrative'),

    // Data sources used to calculate this snapshot
    dataSources: jsonb('data_sources').$type<string[]>().default([]),

    // Sample size / confidence
    sampleSize: integer('sample_size'), // Number of data points analyzed
    confidenceScore: integer('confidence_score'), // 0-100 confidence in the score

    // Timestamps
    recordedAt: timestamp('recorded_at', { withTimezone: true }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    // Historical queries: "Get Pokemon sentiment over time"
    gameTimeIdx: index('idx_sentiment_game_time').on(table.game, table.recordedAt),

    // Dashboard: "Get latest sentiment for each game"
    recordedIdx: index('idx_sentiment_recorded').on(table.recordedAt),

    // Analysis: "Find all extreme fear/greed moments"
    labelIdx: index('idx_sentiment_label').on(table.label),

    // Game-specific queries
    gameIdx: index('idx_sentiment_game').on(table.game),
  }),
);

// =============================================================================
// RELATIONS
// =============================================================================

export const marketReportsRelations = relations(marketReports, ({ many }) => ({
  // Future: Link to comments, user bookmarks, etc.
}));

export const sentimentSnapshotsRelations = relations(sentimentSnapshots, ({ many }) => ({
  // Future: Link to market events, reports that reference this snapshot
}));

// =============================================================================
// TYPES
// =============================================================================

export type MarketReport = InferSelectModel<typeof marketReports>;
export type NewMarketReport = InferInsertModel<typeof marketReports>;

export type SentimentSnapshot = InferSelectModel<typeof sentimentSnapshots>;
export type NewSentimentSnapshot = InferInsertModel<typeof sentimentSnapshots>;

// Enum type exports
export type ReportType = 'daily_snapshot' | 'weekly_deep_dive' | 'flash_alert';
export type SentimentLabel = 'extreme_fear' | 'fear' | 'neutral' | 'greed' | 'extreme_greed';
export type TcgGame = 'pokemon' | 'mtg' | 'lorcana' | 'yugioh' | 'one_piece' | 'flesh_and_blood';

// =============================================================================
// CONSTANTS
// =============================================================================

/**
 * Sentiment score thresholds for label assignment
 */
export const SENTIMENT_THRESHOLDS = {
  extreme_fear: { min: 0, max: 20 },
  fear: { min: 21, max: 40 },
  neutral: { min: 41, max: 60 },
  greed: { min: 61, max: 80 },
  extreme_greed: { min: 81, max: 100 },
} as const;

/**
 * Default TTL for different report types (in hours)
 */
export const REPORT_TTL_HOURS = {
  daily_snapshot: 24,
  weekly_deep_dive: 168, // 7 days
  flash_alert: 4, // Short-lived breaking news
} as const;

/**
 * Helper to get sentiment label from score
 */
export function getSentimentLabel(score: number): SentimentLabel {
  if (score <= 20) return 'extreme_fear';
  if (score <= 40) return 'fear';
  if (score <= 60) return 'neutral';
  if (score <= 80) return 'greed';
  return 'extreme_greed';
}
